baseURL = 'https://bookish-list.gitlab.io/backend'
languageCode = 'en-us'
title = 'Bookish List'
theme = "geekdoc"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9
  [markup.asciidocext]
    extensions = ["asciidoctor-diagram"]
    workingFolderCurrent = true
    preserveTOC = true
    [markup.asciidocext.attributes]
      source-highlighter = "rouge"
      rouge-style = "github"
      rouge-css = "style"
      icons = "font"
      ref-less = "https://less.works/[LeSS]"

[taxonomies]
   tag = "tags"

[params]
  geekdocLogo = "logo.png"

[security]
[security.exec]
allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^asciidoctor$']

