name: Documentation Website

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: doc

jobs:
  documentation:
    name: Documentation
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - run: gem install asciidoctor
      - run: gem install asciidoctor-rouge
      - run: gem install asciidoctor-bibtex
      - run: gem install asciimath

      - name: Run Hugo
        run: |
          mkdir -p themes/geekdoc/
          curl -L https://github.com/thegeeklab/hugo-geekdoc/releases/latest/download/hugo-geekdoc.tar.gz | tar -xz -C themes/geekdoc/ --strip-components=1
          hugo --source ./ --destination public/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
